server:
  port: 3000
  max-http-header-size: 102400
#  设定token长度上限

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anti-fraud #?servierTimezone=UTC
    username: root
    password: mhi7UeyXtm
  redis:
    host: 127.0.0.1
    port: 6379
    password: 666666
  mail:
    default-encoding: UTF-8
#    host: smtp.qq.com
    host: smtp.sina.com
#    username: 160850241@qq.com
    username: chenzczczczc@sina.com
#    password: hchoqtaezpqsbije
    password: f2afcea9b0b0a43d
    properties: # 配置以SSL的方式发送, 这个需要使用这种方式并且端口是465
      mail:
        smtp:
        #          auth: true
        #            ssl:
        #              enable: true
        #                socketFactory:
        #                  class: com.sun.mail.util.MailSSLSocketFactory
        #                  fallback: false
        #        debug: true
        auth: true
        starttls:
          enable: true
          required: true
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory
          port: 465

spring mvc:
  hiddenmethod:
    filter:
      enabled: true



#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
