
server:
  port: 3000

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anti-fraud #?servierTimezone=UTC
    username: root
    password: mhi7UeyXtm

spring mvc:
  hiddenmethod:
    filter:
      enabled: true


#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
