server:
  port: 3000
  max-http-header-size: 102400
#  设定token长度上限

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anti-fraud #?servierTimezone=UTC
    username: root
    password: mhi7UeyXtm
  redis:
    host: 127.0.0.1
    port: 6379
    password: 666666
  mail:
      host: smtp.qq.com
      username: 160850241@qq.com
      password: hchoqtaezpqsbije
      port: 25
#      port:465
#      465是基于SSL协议 25是名文传输
      default-encoding: utf-8

spring mvc:
  hiddenmethod:
    filter:
      enabled: true



#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
